### ISSUE TITLE
Broken "performance analysis notes" link

### ISSUE THREAD

**Issue by mwhittaker** [cornell-cs5220-f15/cornell-cs5220-f15.github.io#2]
The "performance analysis notes" link on the [last slide of the first lecture](http://cornell-cs5220-f15.github.io/slides/intro.html#/22) is broken. Currently, it links to `http://cornell-cs5220-f15.github.io/2015/08/15/performance.html`, but I think it ought to link to `http://cornell-cs5220-f15.github.io/2015/08/10/performance.html`. I don't have Jekyll installed or know enough about it to know how to fix the link or check that it's fixed, so  I thought I'd open an issue instead of a pull request.

**Comment by dbindel** [comment]
Thanks -- your fix is absolutely right.

**Comment by mwhittaker** [comment]
Sweet! Glad to help :smile:
